export default function handler(req, res) {
    const values = {

        // ========== CHROMAS (Tier 3) ==========
        "C. Traveler's Gun": 225000,
        "Chroma Traveler's Gun": 225000,
        "Chroma Evergun": 83000,
        "Chroma Evergreen": 60000,
        "Chroma Bauble": 38000,
        "C. Constellation": 36000,
        "Chroma Constellation": 36000,
        "C. Vampire's Gun": 35000,
        "Chroma Vampire's Gun": 35000,
        "Chroma Alienbeam": 30000,

        // ========== CHROMAS (Tier 2) ==========
        "Chroma Raygun": 15500,
        "Chroma Sunrise": 11250,
        "C. Snowcannon": 8500,
        "Chroma Snowcannon": 8500,
        "Chroma Blizzard": 8000,
        "Chroma Sunset": 6500,
        "C. Snow Dagger": 5750,
        "Chroma Snow Dagger": 5750,
        "C. Heart Wand": 5000,
        "Chroma Heart Wand": 5000,
        "Chroma Treat": 5000,
        "Chroma Snowstorm": 4250,
        "Chroma Watergun": 3400,
        "Chroma Sweet": 3000,
        "Chroma Ornament": 2750,

        // ========== CHROMAS (Tier 1) ==========
        "Chroma Darkbringer": 80,
        "Chroma Lightbringer": 75,
        "Chroma Luger": 57,
        "Chroma Candleflame": 48,
        "Chroma Laser": 48,
        "Chroma Elderwood Blade": 47,
        "Chroma Swirly Gun": 47,
        "Chroma Deathshard": 42,
        "Chroma Slasher": 42,
        "Chroma Cookiecane": 40,
        "Chroma Shark": 40,
        "Chroma Fang": 38,
        "Chroma Gemstone": 35,
        "Chroma Heat": 35,
        "Chroma Gingerblade": 33,
        "Chroma Saw": 33,
        "Chroma Seer": 33,
        "Chroma Tides": 32,
        "Chroma Boneblade": 28,

        // ========== ANCIENTS (Special) ==========
        "Nik's Scythe": 999999999, // Priceless

        // ========== ANCIENTS (Tier 2) ==========
        "Gingerscope": 17000,
        "Traveler's Axe": 8400,
        "Celestial": 1725,
        "Vampire's Axe": 925,
        "Harvester": 300,
        "Icepiercer": 200,

        // ========== ANCIENTS (Tier 1) ==========
        "Icebreaker": 85,
        "Batwing": 50,
        "Elderwood Scythe": 48,
        "Swirly Axe": 45,
        "Hallowscythe": 35,
        "Logchopper": 20,
        "Icewing": 15,

        // ========== GODLIES (Tier 3) ==========
        "Traveler's Gun": 4500,
        "Evergun": 3350,
        "Constellation": 2600,
        "Evergreen": 2500,
        "Turkey": 2425,
        "Alienbeam": 2100,
        "Vampire's Gun": 1700,
        "Darkshot": 1360,
        "Darksword": 1340,
        "Raygun": 1200,
        "Blossom": 1160,
        "Sakura": 1150,
        "Sunrise": 1000,
        "Snowcannon": 925,
        "Bauble": 900,
        "Sunset": 525,
        "Heart Wand": 475,
        "Soul": 370,
        "Spirit": 360,
        "Flora": 300,
        "Rainbow Gun": 300,
        "Bloom": 290,
        "Rainbow": 290,
        "Snow Dagger": 260,
        "Flowerwood Gun": 205,
        "Flowerwood": 200,
        "Xenoknife": 200,
        "Xenoshot": 200,
        "Ocean": 180,
        "Watergun": 175,
        "Waves": 175,
        "Treat": 175,
        "Sweet": 170,
        "Blizzard": 155,
        "Snowstorm": 155,
        "Bat": 125,
        "Borealis": 105,
        "Australis": 100,
        "Candy": 100,
        "Heartblade": 80,
        "Darkbringer": 42,
        "Lightbringer": 38,
        "Luger": 50,
        "Red Luger": 45,
        "Green Luger": 30,
        "Candleflame": 42,
        "Elderwood Blade": 42,
        "Makeshift": 42,
        "Phantom": 42,
        "Spectre": 42,
        "Elderwood Revolver": 42,
        "Iceblaster": 42,
        "Sugar": 42,

        // ========== UNIQUES ==========
        "Corrupt": 600,

        // ========== LEGENDARIES (Special) ==========
        "JD": 35,

        // ========== LEGENDARIES (Tier 3) ==========
        "Latte (Gun)": 130,
        "Latte (Knife)": 130,
        "Cotton Candy": 40,
        "Beach": 30,
        "Traveler (Gun)": 25,
        "Spectral (Knife)": 20,
        "Vampire (Gun)": 20,
        "Aurora (Gun)": 13,
        "Cavern (Knife)": 7,
        "Skulls": 7,
        "Broken": 7,
        "Ginger (Gun)": 6,
        "Arctic (Gun)": 5,
        "Icedriller": 5,
        "Nightsky": 5,
        "Ghost (Knife)": 5,
        "Bunnies": 4,
        "Red Scratch": 4,
        "Vampire (Knife)": 3,
        "Witched": 3,
        "Blue Elite": 3,
        "Green Elite": 3,
        "Santa's Magic": 3,
        "Santa's Spirit": 3,
        "Aurora (Knife)": 2,
        "Spectral (Gun)": 2,

        // ========== VINTAGE ==========
        "Ghost": 10,
        "Blood": 8,
        "Laser": 8,
        "America": 7,
        "Prince": 6,
        "Shadow": 6,
        "Phaser": 5,
        "Cowboy": 4,
        "Golden": 4,
        "Splitter": 3,

        // ========== OTHER GODLY-TIER ITEMS ==========
        "Fang": 10,
        "Heat": 10,
        "Tides": 10,
        "Slasher": 18,
        "Shark": 23,
        "Saw": 7,
        "Deathshard": 15,
        "Gemstone": 17,
        "Gingerblade": 17,
        "Virtual": 17,
        "Battleaxe": 12,
        "Battleaxe II": 18,
        "Bioblade": 10,
        "Boneblade": 7,
        "Chill": 10,
        "Clockwork": 10,
        "Cookiecane": 18,
        "Eternal": 8,
        "Eternal II": 8,
        "Eternal III": 10,
        "Eternal IV": 10,
        "Eternalcane": 17,
        "Frostbite": 7,
        "Frostsaber": 10,
        "Ghostblade": 7,
        "Gingermint": 18,
        "Ginger Luger": 20,
        "Handsaw": 8,
        "Hallow's Blade": 8,
        "Hallow's Edge": 8,
        "Ice Dragon": 7,
        "Ice Shard": 7,
        "Jinglegun": 17,
        "Lugercane": 18,
        "Minty": 18,
        "Nebula": 15,
        "Nightblade": 22,
        "Old Glory": 18,
        "Peppermint": 4,
        "Pixel": 20,
        "Plasmablade": 20,
        "Plasmabeam": 22,
        "Prismatic": 7,
        "Pumpking": 7,
        "Spider": 10,
        "Swirly Blade": 15,
        "Vampire's Edge": 15,
        "Winter's Edge": 5,
        "Xmas": 8,

        // ========== SEERS ==========
        "Blue Seer": 3,
        "Purple Seer": 3,
        "Red Seer": 3,
        "Seer": 3,
        "Orange Seer": 2,
        "Yellow Seer": 2,
    };

    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json(values);
        }
